// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDailyHerping.Models;

namespace MyDailyHerping.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210403225048_ChangeTypeofLatLong")]
    partial class ChangeTypeofLatLong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyDailyHerping.Models.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("MyDailyHerping.Models.Observation", b =>
                {
                    b.Property<int>("ObservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtAdulte")
                        .HasColumnType("int");

                    b.Property<int>("QtEggs")
                        .HasColumnType("int");

                    b.Property<int>("QtFemale")
                        .HasColumnType("int");

                    b.Property<int>("QtJuvenile")
                        .HasColumnType("int");

                    b.Property<int>("QtLarva")
                        .HasColumnType("int");

                    b.Property<int>("QtMale")
                        .HasColumnType("int");

                    b.Property<int>("QtReproduction")
                        .HasColumnType("int");

                    b.Property<int>("QtShed")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObservationID");

                    b.HasIndex("AreaID")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("MyDailyHerping.Models.Observation", b =>
                {
                    b.HasOne("MyDailyHerping.Models.Area", "Area")
                        .WithOne("Observation")
                        .HasForeignKey("MyDailyHerping.Models.Observation", "AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("MyDailyHerping.Models.Area", b =>
                {
                    b.Navigation("Observation");
                });
#pragma warning restore 612, 618
        }
    }
}
